repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: .venv/bin/mypy
        args: [backend/]
        types: [python]
        pass_filenames: false
