# Generated by Django 6.0.3 on 2026-03-28 22:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("send_money", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corridor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_currency", models.CharField(max_length=3)),
                ("destination_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=9, max_digits=19)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "exchange_rates",
                "unique_together": {("source_currency", "destination_currency")},
            },
        ),
        migrations.CreateModel(
            name="TransferAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=128)),
                ("user_id", models.CharField(blank=True, max_length=128)),
                ("action", models.CharField(max_length=50)),
                ("langfuse_trace_id", models.CharField(blank=True, max_length=128)),
                (
                    "langfuse_observation_id",
                    models.CharField(blank=True, max_length=128),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transfer",
                    models.ForeignKey(
                        db_column="transfer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="send_money.transferrecord",
                    ),
                ),
            ],
            options={
                "db_table": "transfer_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
