# Generated by Django 6.0.3 on 2026-03-28 23:04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("send_money", "0002_alter_corridor_id_exchangerate_transferauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferrecord",
            name="amount",
            field=models.DecimalField(decimal_places=9, max_digits=19),
        ),
        migrations.AlterField(
            model_name="transferrecord",
            name="fee",
            field=models.DecimalField(
                decimal_places=9, default=Decimal("0"), max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="transferrecord",
            name="receive_amount",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=19, null=True
            ),
        ),
        migrations.CreateModel(
            name="UserAccountRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=128, unique=True)),
                ("password_hash", models.CharField(max_length=512)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=9, default=Decimal("0"), max_digits=19
                    ),
                ),
                ("balance_currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_accounts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", Decimal("0"))),
                        name="account_balance_non_negative",
                    )
                ],
            },
        ),
    ]
