# Generated by Django 6.0.3 on 2026-03-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_money', '0003_alter_transferrecord_amount_alter_transferrecord_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='corridor',
            table='send_money_corridors',
        ),
        migrations.AlterModelTable(
            name='exchangerate',
            table='send_money_exchange_rates',
        ),
        migrations.AlterModelTable(
            name='transferauditlog',
            table='send_money_transfer_audit_logs',
        ),
        migrations.AlterModelTable(
            name='transferrecord',
            table='send_money_transfers',
        ),
        migrations.AlterModelTable(
            name='useraccountrecord',
            table='send_money_user_accounts',
        ),
    ]
